name: vexa
description: A new Flutter project called VEXA.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  agora_rtc_engine: ^6.3.2
  socket_io_client: ^2.0.3+1
  mobile_scanner: ^5.1.1
  http: ^1.2.1
  wakelock_plus: ^1.2.8
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
